=== ML-PA-Consulting-GmbH/trivy/pkg/dependency/parser/generic/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "packageName": {
      "type": "string"
    },
    "packageVersion": {
      "type": "string"
    },
    "packageLicense": {
      "type": "string"
    },
    "packageCopyright": {
      "type": "string"
    },
    "dependencies": {
      "type": "object",
      "properties": {
        "packageName": {
          "type": "object",
          "properties": {
            "version": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "license": {
              "type": "string"
            },
            "copyright": {
              "type": "string"
            },
            "checksum": {
              "type": "string"
            }
          },
          "required": [
            "version",
            "source",
            "type"
          ]
        }
      }
    },
    "sourceFiles": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "object",
          "properties": {
            "version": {
              "type": "string"
            },
            "checksum": {
              "type": "string"
            },
            "license": {
              "type": "string"
            },
            "copyright": {
              "type": "string"
            }
          },
          "required": [
            "version",
            "checksum",
            "license"
          ]
        }
      }
    }
  },
  "required": [
    "packageName",
    "packageVersion",
    "dependencies"
  ]
}

=== ML-PA-Consulting-GmbH/trivy/integration/testdata/fixtures/repo/generic/dependencies.json
{
  "packageName": "M2CPos",
  "packageVersion": "2.0 alpha",
  "packageLicense": "GPL 2.1",
  "dependencies": {
    "linuxKernel": {
    	"version": "2.1",
    	"source": "https://github.com/....",
    	"type": "source",
    	"license": "GPL 2.1",
    	"checksum": "SHA256: 12345667"
    },
    "libC": {
    	"version": "12.1",
    	"source": "https://github.com/....",
    	"type": "source",
    	"license": "LGPL 1.2",
    	"checksum": "SHA256: 789321456"
    }
  },
  "sourceFiles": {
    "path/to/FileName.c": {
    	"version": "2.2",
    	"checksum": "SHA256 562145698",
    	"license": "GPL 2.1"
    },
    "path/to/FileName2": {
    	"version": "2.2",
    	"checksum": "SHA256 562145698",
    	"license": "proprietary"
    }
  }
}
